Dataset unification
nbirillo/coding-assistant pull request #11
Opened 2021-03-18 02:15 UTC by artbobrov

2021-03-18 12:32 UTC, nbirillo requested changes
Great

2021-03-18 12:32 UTC, nbirillo commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/unification/CompositeTransformation.kt
> +    private val transformations = arrayListOf(
What do you think about using Reflektion here? I know that is is not fast, but I think for our goals it is ok. In addition, in a couple of weeks we can use compile-time reflection as soon as the [Reflekt](https://github.com/JetBrains-Research/reflekt) is published

2021-03-18 12:32 UTC, nbirillo commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/unification/CompositeTransformation.kt
> +    private val transformations = arrayListOf(
I am not sure I am right, we can discuss it

2021-03-18 12:32 UTC, nbirillo commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/unification/CompositeTransformation.kt
> +            LOG.info { "Current text[$iterationNumber]:\n${psiTree.text}\n\n" }
I think it is DEBUG level

2021-03-18 12:32 UTC, nbirillo commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/unification/CompositeTransformation.kt
> +        } while (!previousTree.textMatches(psiTree.text))
Should we forcefully stop after say 100 iterations or some other value?

2021-03-18 12:32 UTC, nbirillo commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/unification/DatasetUnification.kt
> +interface DatasetUnification {
Please add general description for this interface

2021-03-18 12:32 UTC, nbirillo commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/unification/DatasetUnification.kt
> +    fun transform(dynamicSolution: DynamicSolution): DynamicIntermediateSolution
Probably a better name is `unify` or something like this?

2021-03-18 12:32 UTC, nbirillo commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/unification/DatasetUnification.kt
> +        }
I think we should create a function for it. Also we can use this function in the tests

2021-03-18 12:32 UTC, nbirillo commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/unification/model/DatasetPartialSolution.kt
> + * Dataset partial solution
Please, add more detailed info

2021-03-18 12:32 UTC, nbirillo commented on src/test/kotlin/org/jetbrains/research/ml/coding/assistant/compositeTransformation/CompositeTransformationTest.kt
> +@Ignore
Why should we ignore this test?

2021-03-18 12:32 UTC, nbirillo commented on src/test/kotlin/org/jetbrains/research/ml/coding/assistant/unification/DatasetUnificationTest.kt
> +    fun testBasic() {
Should we assert something? or at least check that there were no errors on run

2021-03-18 12:32 UTC, nbirillo commented on src/test/kotlin/org/jetbrains/research/ml/coding/assistant/unification/DatasetUnificationTest.kt
> +    fun testStuff() {
Very strange name

2021-03-18 12:32 UTC, nbirillo commented on src/test/kotlin/org/jetbrains/research/ml/coding/assistant/unification/DatasetUnificationTest.kt
> +        val inputDir = "/Users/artembobrov/Documents/masters/ast-transform/python/max_digit/"
Please, don't use these names

2021-03-18 12:32 UTC, nbirillo commented on src/test/kotlin/org/jetbrains/research/ml/coding/assistant/unification/DatasetUnificationTest.kt
> +            val path = "/Users/artembobrov/Documents/masters/ast-transform/python"
Absolute path

2021-03-18 12:32 UTC, nbirillo commented on src/test/kotlin/org/jetbrains/research/ml/coding/assistant/compositeTransformation/CompositeTransformationTest.kt
> +class CompositeTransformationTest : ParametrizedBaseWithSdkTest(getTmpProjectDir(true)) {
Please, add more test cases

2021-03-20 04:45 UTC, artbobrov commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/unification/CompositeTransformation.kt
> +    private val transformations = arrayListOf(
mb now it's ok
but back in the days when anonymization problems had been destroying my evenings it wasn't the solution.

2021-03-20 04:50 UTC, artbobrov commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/unification/CompositeTransformation.kt
> +    private val transformations = arrayListOf(
but I personally do not see anything bad in this list.

2021-03-23 13:03 UTC, elena-lyulina requested changes

2021-03-23 13:03 UTC, elena-lyulina commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/unification/CompositeTransformation.kt
> +    private val transformations = arrayListOf(
let's keep it for now and change it if there is extra time left

2021-03-23 13:03 UTC, elena-lyulina commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/unification/CompositeTransformation.kt
> +    private val transformations = arrayListOf(
also, all inner transformation -> all inner transformation**s**

2021-03-23 13:03 UTC, elena-lyulina commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/unification/DatasetUnification.kt
> +import org.jetbrains.research.ml.coding.assistant.solutionSpace.utils.psiCreator.PsiCreator
does solutionSpace package persist in this PR? I don't see it for some reason and my intelliJ cannot find PsiCreator

2021-03-23 13:03 UTC, elena-lyulina commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/unification/model/DatasetPartialSolution.kt
> + * Dataset partial solution
Yeah, it'd be great to define partial solution

2021-03-29 17:46 UTC, elena-lyulina approved these changes
Well done!

2021-03-29 22:01 UTC, merged