Build solution space
nbirillo/coding-assistant pull request #12
Opened 2021-03-18 02:17 UTC by artbobrov

2021-03-18 13:08 UTC, nbirillo requested changes
Great!

2021-03-18 13:08 UTC, nbirillo commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/solutionSpace/SolutionSpace.kt
> +private fun transferGraph(
Please, add some comments

2021-03-18 13:08 UTC, nbirillo commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/solutionSpace/SolutionSpace.kt
> +private var idCounter = 0
Is it ok? using global variables....

2021-03-18 13:08 UTC, nbirillo commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/solutionSpace/SolutionSpaceParts.kt
> + * Solution space vertex
Please, add more detailed comment

2021-03-18 13:08 UTC, nbirillo commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/solutionSpace/SolutionSpaceParts.kt
> +data class SolutionSpaceVertex(
Should we store text since we need it to build PSI to apply GumTree actions?

2021-03-18 13:08 UTC, nbirillo commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/solutionSpace/builder/SolutinoSpaceParts.kt
> +    val representativeSolution: DatasetPartialSolution get() = partialSolutions.first()
Why should we get the first item?

2021-03-18 13:08 UTC, nbirillo commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/solutionSpace/utils/GraphVisualizationUtils.kt
> +private val mxStylesheet.finalSolutionStyle get() = styles[GraphVisualizationUtils.FINAL_SOLUTION_NAME]!!
please, don't use `!!`

2021-03-18 13:08 UTC, nbirillo commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/solutionSpace/builder/WeightedEdge.kt
> +open class WeightedEdge : DefaultWeightedEdge() {
Please, add description

2021-03-18 13:08 UTC, nbirillo commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/solutionSpace/utils/psiCreator/PsiCreator.kt
> +interface PsiFileWrapper : PsiFile {
Please, add a detailed description

2021-03-18 13:08 UTC, nbirillo commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/solutionSpace/utils/psiCreator/PsiCreator.kt
> +interface PsiCreator {
Please, add a detailed description

2021-03-18 13:08 UTC, nbirillo commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/solutionSpace/utils/psiCreator/PsiCreator.kt
> +    private val extension: String = ".py"
Please, use a value from extension enum class

2021-03-18 13:08 UTC, nbirillo commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/solutionSpace/weightCalculator/EdgeActionsCache.kt
> +class EdgeActionsCache(
Please, add some description

2021-03-18 13:08 UTC, nbirillo commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/solutionSpace/weightCalculator/EdgeWeightCalculator.kt
> +class CustomEdgeWeightCalculator(
Please, add some description of how you calculate Weight

2021-03-18 13:08 UTC, nbirillo commented on src/test/kotlin/org/jetbrains/research/ml/coding/assistant/problems/AnonymizationProblemTest.kt
> +class AnonymizationProblemTest : ParametrizedBaseWithSdkTest(getResourcesRootPath(::AnonymizationProblemTest)) {
Please, add some comment with explanation what is anonymization problem

2021-03-20 07:09 UTC, artbobrov commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/solutionSpace/builder/SolutinoSpaceParts.kt
> +    val representativeSolution: DatasetPartialSolution get() = partialSolutions.first()
Any partial solution fits.
The vertex contains a list of associated partial solutions and all code fragments are identical

2021-03-20 07:59 UTC, artbobrov commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/solutionSpace/weightCalculator/EdgeWeightCalculator.kt
> +class CustomEdgeWeightCalculator(
<img width="684" alt="Снимок экрана 2021-03-20 в 10 59 18" src="https://user-images.githubusercontent.com/24722656/111863238-583f9500-896b-11eb-8844-01449b9c5c05.png">

2021-03-26 06:00 UTC, elena-lyulina requested changes

2021-03-26 06:00 UTC, elena-lyulina commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/solutionSpace/SolutionSpace.kt
> +        fun transferEdges(edges: Iterable<SolutionSpaceGraphEdge>, isOutgoing: Boolean) {
I'm not exactly sure what happens if you define nested functions in a loop, but maybe it's better to move it outside?

2021-03-26 06:00 UTC, elena-lyulina commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/solutionSpace/builder/SolutinoSpaceParts.kt
> +        return true
for me this        
`return (this === other) || (javaClass == other?.javaClass && partialSolutions == (other as SolutionSpaceGraphVertex).partialSolutions)`
 is a little bit more readable, but it's up to you

2021-03-26 10:15 UTC, artbobrov commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/solutionSpace/SolutionSpace.kt
> +        fun transferEdges(edges: Iterable<SolutionSpaceGraphEdge>, isOutgoing: Boolean) {
inner functions could use the context of the outer function.
The compiler moves all inner functions outside with additional argument – outer function context.
So, nothing special happens. but okey

2021-03-26 10:29 UTC, artbobrov commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/solutionSpace/builder/SolutinoSpaceParts.kt
> +        return true
it is, but this code is generated by IntelliJ. I guess this code style is designed to be easily extendable for other fields

2021-03-29 17:45 UTC, elena-lyulina approved these changes
Cool, thanks

2021-03-29 21:55 UTC, merged