Solution Space serialization
nbirillo/coding-assistant pull request #13
Opened 2021-03-18 02:18 UTC by artbobrov

2021-03-18 13:34 UTC, nbirillo requested changes
Great

2021-03-18 13:34 UTC, nbirillo commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/solutionSpace/serialization/TreeContextSerializer.kt
> +          label="\n" --> label=" "
We don't need fix it since we remove whitespace. but it is a great idea to add this comment

2021-03-18 13:34 UTC, nbirillo commented on src/test/kotlin/org/jetbrains/research/ml/coding/assistant/solutionSpace/serialization/SolutionSpaceSerializerTest.kt
> +    var outFile: String? = null
It seems you don't use these variables

2021-03-18 13:34 UTC, nbirillo commented on src/test/kotlin/org/jetbrains/research/ml/coding/assistant/solutionSpace/serialization/SolutionSpaceSerializerTest.kt
> +    """.trimIndent()
Please, add more test cases. It would be great if you get code from input files

2021-03-18 13:34 UTC, nbirillo commented on src/test/kotlin/org/jetbrains/research/ml/coding/assistant/solutionSpace/serialization/SolutionSpaceSerializerTest.kt
> +        const val INPUT_DIR: String = "/Users/artembobrov/Documents/masters/ast-transform/python/max_3"
Please, don't use absolute paths

2021-03-26 06:08 UTC, elena-lyulina reviewed
Nicely done, +1 to Nastya's comments

2021-03-29 17:48 UTC, elena-lyulina approved these changes
Everything's fixed, thanks

2021-03-29 20:32 UTC, merged