Report Generation
nbirillo/coding-assistant pull request #14
Opened 2021-03-18 02:19 UTC by artbobrov

2021-03-18 13:42 UTC, nbirillo requested changes
Great!

2021-03-18 13:42 UTC, nbirillo commented on src/main/kotlin/org/jetbrains/research/ml/coding/assistant/report/HintReportGenerator.kt
> +class CompositeMarkdownHintReportGenerator(private val generator: HintReportGenerator) {
Please, add some description

2021-03-26 06:11 UTC, elena-lyulina approved these changes
Cool!

2021-03-29 17:49 UTC, elena-lyulina approved these changes
Approve, thanks

2021-03-29 20:18 UTC, merged